/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appDmsRouteRouteImport } from './routes/(app)/dms/route'
import { Route as appAdminRouteRouteImport } from './routes/(app)/admin/route'
import { Route as appDmsIndexRouteImport } from './routes/(app)/dms/index'
import { Route as appDmsChannelIdRouteImport } from './routes/(app)/dms/$channelId'
import { Route as appAdminCodesRouteImport } from './routes/(app)/admin/codes'
import { Route as appGuildsGuildIdRouteRouteImport } from './routes/(app)/guilds/$guildId/route'
import { Route as appGuildsGuildIdIndexRouteImport } from './routes/(app)/guilds/$guildId/index'
import { Route as appGuildsGuildIdSettingsRouteImport } from './routes/(app)/guilds/$guildId/settings'
import { Route as appDmsNewUserIdRouteImport } from './routes/(app)/dms/new/$userId'
import { Route as appGuildsGuildIdChannelsChannelIdRouteImport } from './routes/(app)/guilds/$guildId/channels/$channelId'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appDmsRouteRoute = appDmsRouteRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminRouteRoute = appAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appRouteRoute,
} as any)
const appDmsIndexRoute = appDmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDmsRouteRoute,
} as any)
const appDmsChannelIdRoute = appDmsChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => appDmsRouteRoute,
} as any)
const appAdminCodesRoute = appAdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => appAdminRouteRoute,
} as any)
const appGuildsGuildIdRouteRoute = appGuildsGuildIdRouteRouteImport.update({
  id: '/guilds/$guildId',
  path: '/guilds/$guildId',
  getParentRoute: () => appRouteRoute,
} as any)
const appGuildsGuildIdIndexRoute = appGuildsGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appGuildsGuildIdRouteRoute,
} as any)
const appGuildsGuildIdSettingsRoute =
  appGuildsGuildIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appGuildsGuildIdRouteRoute,
  } as any)
const appDmsNewUserIdRoute = appDmsNewUserIdRouteImport.update({
  id: '/new/$userId',
  path: '/new/$userId',
  getParentRoute: () => appDmsRouteRoute,
} as any)
const appGuildsGuildIdChannelsChannelIdRoute =
  appGuildsGuildIdChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => appGuildsGuildIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof appAdminRouteRouteWithChildren
  '/dms': typeof appDmsRouteRouteWithChildren
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/guilds/$guildId': typeof appGuildsGuildIdRouteRouteWithChildren
  '/admin/codes': typeof appAdminCodesRoute
  '/dms/$channelId': typeof appDmsChannelIdRoute
  '/dms/': typeof appDmsIndexRoute
  '/dms/new/$userId': typeof appDmsNewUserIdRoute
  '/guilds/$guildId/settings': typeof appGuildsGuildIdSettingsRoute
  '/guilds/$guildId/': typeof appGuildsGuildIdIndexRoute
  '/guilds/$guildId/channels/$channelId': typeof appGuildsGuildIdChannelsChannelIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof appAdminRouteRouteWithChildren
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/admin/codes': typeof appAdminCodesRoute
  '/dms/$channelId': typeof appDmsChannelIdRoute
  '/dms': typeof appDmsIndexRoute
  '/dms/new/$userId': typeof appDmsNewUserIdRoute
  '/guilds/$guildId/settings': typeof appGuildsGuildIdSettingsRoute
  '/guilds/$guildId': typeof appGuildsGuildIdIndexRoute
  '/guilds/$guildId/channels/$channelId': typeof appGuildsGuildIdChannelsChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/admin': typeof appAdminRouteRouteWithChildren
  '/(app)/dms': typeof appDmsRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/guilds/$guildId': typeof appGuildsGuildIdRouteRouteWithChildren
  '/(app)/admin/codes': typeof appAdminCodesRoute
  '/(app)/dms/$channelId': typeof appDmsChannelIdRoute
  '/(app)/dms/': typeof appDmsIndexRoute
  '/(app)/dms/new/$userId': typeof appDmsNewUserIdRoute
  '/(app)/guilds/$guildId/settings': typeof appGuildsGuildIdSettingsRoute
  '/(app)/guilds/$guildId/': typeof appGuildsGuildIdIndexRoute
  '/(app)/guilds/$guildId/channels/$channelId': typeof appGuildsGuildIdChannelsChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/dms'
    | '/profile'
    | '/login'
    | '/signup'
    | '/'
    | '/guilds/$guildId'
    | '/admin/codes'
    | '/dms/$channelId'
    | '/dms/'
    | '/dms/new/$userId'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId/'
    | '/guilds/$guildId/channels/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/profile'
    | '/login'
    | '/signup'
    | '/'
    | '/admin/codes'
    | '/dms/$channelId'
    | '/dms'
    | '/dms/new/$userId'
    | '/guilds/$guildId/settings'
    | '/guilds/$guildId'
    | '/guilds/$guildId/channels/$channelId'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/admin'
    | '/(app)/dms'
    | '/(app)/profile'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/'
    | '/(app)/guilds/$guildId'
    | '/(app)/admin/codes'
    | '/(app)/dms/$channelId'
    | '/(app)/dms/'
    | '/(app)/dms/new/$userId'
    | '/(app)/guilds/$guildId/settings'
    | '/(app)/guilds/$guildId/'
    | '/(app)/guilds/$guildId/channels/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dms': {
      id: '/(app)/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof appDmsRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin': {
      id: '/(app)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appAdminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dms/': {
      id: '/(app)/dms/'
      path: '/'
      fullPath: '/dms/'
      preLoaderRoute: typeof appDmsIndexRouteImport
      parentRoute: typeof appDmsRouteRoute
    }
    '/(app)/dms/$channelId': {
      id: '/(app)/dms/$channelId'
      path: '/$channelId'
      fullPath: '/dms/$channelId'
      preLoaderRoute: typeof appDmsChannelIdRouteImport
      parentRoute: typeof appDmsRouteRoute
    }
    '/(app)/admin/codes': {
      id: '/(app)/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof appAdminCodesRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
    '/(app)/guilds/$guildId': {
      id: '/(app)/guilds/$guildId'
      path: '/guilds/$guildId'
      fullPath: '/guilds/$guildId'
      preLoaderRoute: typeof appGuildsGuildIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/guilds/$guildId/': {
      id: '/(app)/guilds/$guildId/'
      path: '/'
      fullPath: '/guilds/$guildId/'
      preLoaderRoute: typeof appGuildsGuildIdIndexRouteImport
      parentRoute: typeof appGuildsGuildIdRouteRoute
    }
    '/(app)/guilds/$guildId/settings': {
      id: '/(app)/guilds/$guildId/settings'
      path: '/settings'
      fullPath: '/guilds/$guildId/settings'
      preLoaderRoute: typeof appGuildsGuildIdSettingsRouteImport
      parentRoute: typeof appGuildsGuildIdRouteRoute
    }
    '/(app)/dms/new/$userId': {
      id: '/(app)/dms/new/$userId'
      path: '/new/$userId'
      fullPath: '/dms/new/$userId'
      preLoaderRoute: typeof appDmsNewUserIdRouteImport
      parentRoute: typeof appDmsRouteRoute
    }
    '/(app)/guilds/$guildId/channels/$channelId': {
      id: '/(app)/guilds/$guildId/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/guilds/$guildId/channels/$channelId'
      preLoaderRoute: typeof appGuildsGuildIdChannelsChannelIdRouteImport
      parentRoute: typeof appGuildsGuildIdRouteRoute
    }
  }
}

interface appAdminRouteRouteChildren {
  appAdminCodesRoute: typeof appAdminCodesRoute
}

const appAdminRouteRouteChildren: appAdminRouteRouteChildren = {
  appAdminCodesRoute: appAdminCodesRoute,
}

const appAdminRouteRouteWithChildren = appAdminRouteRoute._addFileChildren(
  appAdminRouteRouteChildren,
)

interface appDmsRouteRouteChildren {
  appDmsChannelIdRoute: typeof appDmsChannelIdRoute
  appDmsIndexRoute: typeof appDmsIndexRoute
  appDmsNewUserIdRoute: typeof appDmsNewUserIdRoute
}

const appDmsRouteRouteChildren: appDmsRouteRouteChildren = {
  appDmsChannelIdRoute: appDmsChannelIdRoute,
  appDmsIndexRoute: appDmsIndexRoute,
  appDmsNewUserIdRoute: appDmsNewUserIdRoute,
}

const appDmsRouteRouteWithChildren = appDmsRouteRoute._addFileChildren(
  appDmsRouteRouteChildren,
)

interface appGuildsGuildIdRouteRouteChildren {
  appGuildsGuildIdSettingsRoute: typeof appGuildsGuildIdSettingsRoute
  appGuildsGuildIdIndexRoute: typeof appGuildsGuildIdIndexRoute
  appGuildsGuildIdChannelsChannelIdRoute: typeof appGuildsGuildIdChannelsChannelIdRoute
}

const appGuildsGuildIdRouteRouteChildren: appGuildsGuildIdRouteRouteChildren = {
  appGuildsGuildIdSettingsRoute: appGuildsGuildIdSettingsRoute,
  appGuildsGuildIdIndexRoute: appGuildsGuildIdIndexRoute,
  appGuildsGuildIdChannelsChannelIdRoute:
    appGuildsGuildIdChannelsChannelIdRoute,
}

const appGuildsGuildIdRouteRouteWithChildren =
  appGuildsGuildIdRouteRoute._addFileChildren(
    appGuildsGuildIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appAdminRouteRoute: typeof appAdminRouteRouteWithChildren
  appDmsRouteRoute: typeof appDmsRouteRouteWithChildren
  appProfileRoute: typeof appProfileRoute
  appIndexRoute: typeof appIndexRoute
  appGuildsGuildIdRouteRoute: typeof appGuildsGuildIdRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminRouteRoute: appAdminRouteRouteWithChildren,
  appDmsRouteRoute: appDmsRouteRouteWithChildren,
  appProfileRoute: appProfileRoute,
  appIndexRoute: appIndexRoute,
  appGuildsGuildIdRouteRoute: appGuildsGuildIdRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
