/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appProfileRouteImport } from './routes/(app)/profile'
import { Route as appAdminRouteRouteImport } from './routes/(app)/admin/route'
import { Route as appAdminCodesRouteImport } from './routes/(app)/admin/codes'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminRouteRoute = appAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminCodesRoute = appAdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => appAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof appAdminRouteRouteWithChildren
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/admin/codes': typeof appAdminCodesRoute
}
export interface FileRoutesByTo {
  '/admin': typeof appAdminRouteRouteWithChildren
  '/profile': typeof appProfileRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/admin/codes': typeof appAdminCodesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/admin': typeof appAdminRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/admin/codes': typeof appAdminCodesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/admin' | '/profile' | '/login' | '/signup' | '/' | '/admin/codes'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin' | '/profile' | '/login' | '/signup' | '/' | '/admin/codes'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/admin'
    | '/(app)/profile'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/'
    | '/(app)/admin/codes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin': {
      id: '/(app)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appAdminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin/codes': {
      id: '/(app)/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof appAdminCodesRouteImport
      parentRoute: typeof appAdminRouteRoute
    }
  }
}

interface appAdminRouteRouteChildren {
  appAdminCodesRoute: typeof appAdminCodesRoute
}

const appAdminRouteRouteChildren: appAdminRouteRouteChildren = {
  appAdminCodesRoute: appAdminCodesRoute,
}

const appAdminRouteRouteWithChildren = appAdminRouteRoute._addFileChildren(
  appAdminRouteRouteChildren,
)

interface appRouteRouteChildren {
  appAdminRouteRoute: typeof appAdminRouteRouteWithChildren
  appProfileRoute: typeof appProfileRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAdminRouteRoute: appAdminRouteRouteWithChildren,
  appProfileRoute: appProfileRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
